version: '3.9'
services:
  server:
    hostname: ${NX_SERVER_NAME}
    domainname: ${DOMAIN} 
    restart: unless-stopped
    depends_on:
      - postgres
    image: netxms-docker/server:latest
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
      args:
        TZ: ${TZ}
        LOCALE: ${LOCALE}
    volumes:
      - ./docker/server/entrypoint.d:/entrypoint.d:ro
      - ./config/netxmsd.conf:/etc/netxmsd.conf
      - ./config/config_ap:/var/lib/netxms/config_ap
      - ./config/extra-mibs:/mnt/extra-mibs
    ports:
      - "4701:4701"
      - "4703:4703"
      - "4747:4747"
      - "514:514/udp"
      - "162:162/udp"
    stdin_open: true

  postgres:
    hostname: ${NX_POSTGRES_NAME}
    domainname: ${DOMAIN}
    restart: unless-stopped
    image: timescale/timescaledb:latest-pg13
    build:
      context: ./
      dockerfile: docker/postgres/Dockerfile
      args:
        TZ: ${TZ}
        LOCALE: ${LOCALE}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      TZ: ${TZ}
      PGTZ: ${TZ}
      POSTGRES_USER: netxms
      POSTGRES_PASSWORD: netxms
      POSTGRES_DB: netxms
  agent:
    #hostname: agent
    domainname: ${DOMAIN}
    restart: unless-stopped
    image: netxms-agent:latest
    build:
      context: ./
      dockerfile: docker/agent/Dockerfile
      args:
        TZ: ${TZ}
        LOCALE: ${LOCALE}
    environment:
        NX_AGENTD_NAME_PREFIX: ${NX_AGENTD_NAME_PREFIX}
    ports:
      - "4700:4700"
    volumes:
      - ./docker/agent/entrypoint.d:/entrypoint.d:ro
      - ./config/nxagentd.conf:/etc/nxagentd.conf
      - ./config/nxagentd.conf.d:/tmp/nxagentd.conf.d
  cli:
    hostname: cli
    domainname: ${DOMAIN}
    image: netxms-docker/server:latest
    profiles: ["cli"]
    command: bash
    tty: true
    environment:
      NO_ENTRYPOINTD: 1
    volumes:
      - ./config/netxmsd.conf:/etc/netxmsd.conf:ro
      - ./config/config_ap:/var/lib/netxms/config_ap
      - ./config/extra-mibs:/mnt/extra-mibs
 
